[package]
name = "bgpkit-parser-dump"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bgpkit-parser = {git="https://github.com/bgpkit/bgpkit-parser.git", branch="main"}
